### ISSUE TITLE
from oct_converter.readers import E2E fails

### ISSUE THREAD

**Issue by karakays** [marksgraham/OCT-Converter#19]
I am trying to run examples/demo_e2e_extraction.py but it fails on the import with following below.

Can you please guide me how to run examples? My python version is 3.6.10.

```
$ python examples/demo_e2e_extraction.py

Traceback (most recent call last):
  File "demo_e2e_extraction.py", line 1, in <module>
    from oct_converter.readers import E2E
  File "/home/karakays/.pyenv/versions/3.6.10/lib/python3.6/site-packages/oct_converter/readers/__init__.py", line 5, in <module>
    from .fda import FDA
  File "/home/karakays/.pyenv/versions/3.6.10/lib/python3.6/site-packages/oct_converter/readers/fda.py", line 4, in <module>
    from pylibjpeg import decode
  File "/home/karakays/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pylibjpeg/__init__.py", line 29, in <module>
    import pydicom
  File "/home/karakays/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pydicom/__init__.py", line 32, in <module>
    from pydicom.dataelem import DataElement
  File "/home/karakays/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pydicom/dataelem.py", line 18, in <module>
    from pydicom import config  # don't import datetime_conversion directly
  File "/home/karakays/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pydicom/config.py", line 238, in <module>
    import pydicom.pixel_data_handlers.pylibjpeg_handler as pylibjpeg_handler  # noqa
  File "/home/karakays/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pydicom/pixel_data_handlers/pylibjpeg_handler.py", line 66, in <module>
    import openjpeg
  File "/home/karakays/.pyenv/versions/3.6.10/lib/python3.6/site-packages/openjpeg/__init__.py", line 3, in <module>
    from ._config import DICOM_ENCODERS, DICOM_DECODERS
  File "/home/karakays/.pyenv/versions/3.6.10/lib/python3.6/site-packages/openjpeg/_config.py", line 2, in <module>
    from openjpeg.utils import decode_pixel_data
  File "/home/karakays/.pyenv/versions/3.6.10/lib/python3.6/site-packages/openjpeg/utils.py", line 6, in <module>
    import _openjpeg
  File "openjpeg/_openjpeg.pyx", line 1, in init _openjpeg
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by marksgraham** [comment]
As a first step could you try running on Python 3.7?

**Comment by karakays** [comment]
yes, I managed to run it with 3.7.
Created a PR for this issue here https://github.com/marksgraham/OCT-Converter/pull/20
Can you please check?

**Comment by marksgraham** [comment]
Thanks, have approved.
