### ISSUE TITLE
Errors  about converting .oct to .img 

### ISSUE THREAD

**Issue by daydream-noquitter** [marksgraham/OCT-Converter#49]
First, your work is wonderful but when I try to convert.oct to .img I meet errors.
I used the  program in the samples , [demo_boct_extraction.py](https://github.com/marksgraham/OCT-Converter/blob/master/examples/demo_boct_extraction.py)  
but when I run it, it logs like this. If you have any idea, I will be grateful for your help.

D:\Project\a.zip
Traceback (most recent call last):

  File "D:\Project\demo_boct_extraction.py", line 9, in <module>
    boct = BOCT(filepath)

  File "E:\anaconda\anaconda\lib\site-packages\oct_converter\readers\boct.py", line 64, in __init__
    "magicNumber" / Hex(Int32un),

  File "E:\anaconda\anaconda\lib\site-packages\construct\core.py", line 616, in __rtruediv__
    return Renamed(self, newname=name)

  File "E:\anaconda\anaconda\lib\site-packages\construct\core.py", line 2642, in __init__
    super().__init__(subcon)

  File "E:\anaconda\anaconda\lib\site-packages\construct\core.py", line 675, in __init__
    raise TypeError("subcon should be a Construct field")

TypeError: subcon should be a Construct field

**Comment by marksgraham** [comment]
@Dbrown411 Have you got any ideas here?
@daydream-noquitter are you able to share any imaging files to assist us debugging?

**Comment by Dbrown411** [comment]
@daydream-noquitter Do you have a .OCT file in the folder containing the demo_boct_extraction.py file and have you made the appropriate changes to the filenames? The examples in this repo do not come with example oct files. If yes, could you share the results of "pip list" when called in your environment?
