### ISSUE TITLE
Error with E2E file extraction

### ISSUE THREAD

**Issue by MervThom** [marksgraham/OCT-Converter#68]
Hi I would be grateful for some advice regarding this error please:
(base) [xyz@spectre13 examples]$ python demo_e2e_extraction.py
Traceback (most recent call last):
  File "/lustre/xyz/examples/demo_e2e_extraction.py", line 9, in <module>
    volume.peek(show_contours=True)  # plots a montage of the volume
TypeError: peek() got an unexpected keyword argument 'show_contours'

Many thanks!

**Comment by marksgraham** [comment]
Have you got the latest version installed?

**Comment by MervThom** [comment]
Thanks Mark,
yes installed the latest version using the command (pip install oct-converter); I have python version 3.9 . 
In the demo_e2e_extraction.py, I specified the location of an .E2E (tried with a few different E2E). But getting the same issue.
If I change demo python script to: 
volume.peek()

It shows a Figure 1 (montage of the slices). The script pauses. Once I close figure 1 I get the following error:
Traceback (most recent call last):
  File "/lustre/***/OCT-Converter-master/examples/demo_e2e_extraction_v2.py", line 10, in <module>
    volume.save("{}_{}.avi".format(volume.volume_id, volume.laterality))
AttributeError: 'OCTVolumeWithMetaData' object has no attribute 'volume_id'

Many thanks for your advice on this.

**Comment by marksgraham** [comment]
Hi,

All these errors point towards you having an older version of the tool installed. Both the show_contours argument and the addition of the volune_id attribute are fairly recent. When you run pip list what version of the tool does it show? 

Mark
