### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by Llew21** [marksgraham/OCT-Converter#7]
Hi Mark
I'm afraid I'm completely new to python. I have V3 Shell installed on a windows 10 pc. If I copy and paste :

git clone https://github.com/marksgraham/OCT-Converter.git
pip install -e OCT-Converter

I get a syntax error with the cursor over the c in clone.

I have a Topcon 1000 mk2 which is getting long in the tooth and will have to replace it soon. I would like to export the data from it so that I can view it on a DICOM viewer.

Can your program do bulk conversion? How can the files be linked to the patient after conversion?

Any help much appreciated.

Mark

Mark Jones

**Comment by marksgraham** [comment]
Hi there,

It seems like your first issue is with git, rather than python. Are you sure git is installed on the machine? I don't have much experience with windows but it seems git doesn't come instaled by default, see e.g. [this guide](https://www.computerhope.com/issues/ch001927.htm).

You can use the convertor to do bulk conversion by setting up a little script that loops over all your files and converts each of them. How do you normally link the files to patient - is their name / a patient ID stored in the topcon file? If so I should be able to extract that so it can be saved in the relevant dicom field.

**Comment by Llew21** [comment]
Hi Mark

 

Thanks very much for pointing me in that direction. Never used GIT before.

 

The first line worked ok but I then got the following :

 

Mark@MARK-PC2 MINGW64 ~

$ install -e OCT-Converter

install: unknown option -- e

Try 'install --help' for more information.

 

Mark@MARK-PC2 MINGW64 ~

$ install OCT-Converter

install: missing destination file operand after 'OCT-Converter'

Try 'install --help' for more information.

 

It didn’t like pip either: command not found

 

I’ll try and google it but if you have any ideas?

 

Is the program  GUI or command line based?

 

Regards

 

Mark

**Comment by marksgraham** [comment]
Hi,
The latest versions of python should come with pip installed, do you know if you have python installed? You can download the latest version from [here](https://www.python.org/downloads/).

**Comment by Llew21** [comment]
HI Mark

 

I got a bit further with the mac than the PC but still hit these errors:

 

Collecting imageio-ffmpeg

  Downloading imageio-ffmpeg-0.3.0.tar.gz (13 kB)

ERROR: Could not find a version that satisfies the requirement pylibjpeg (from oct-converter==0.1) (from versions: none)

ERROR: No matching distribution found for pylibjpeg (from oct-converter==0.1)

 

 

Python3 is definitely installed as version returns the correct version number

 

SO close now

 

Regards

 

Mark

**Comment by marksgraham** [comment]
Hi,
Could you run this command:
`pip install --upgrade pip`
and then try
`pip install -e OCT-Converter`

**Comment by Llew21** [comment]
Hi Mark.
I went back to the PC in the end as there was a Python 2.7 installation on the MAC which should not be removed blocking everything. So I got it all installed on the PC.
I modified the fda_extraction file as follows:
filepath = 'Z:\Public\OCT data\3DOCT_DATABASE\DATA\4867.fda'
fda = FDA(filepath)
fundus_image = fda.read_fundus_image()  # returns a  Fundus image with additional metadata if available
fundus_image.save('fda_testing_fundus.jpg')
It opens a terminal window briefly and it closes with no result. 
My fda files are about 11mb. They are given numbers as you can see in the above paste. Topcon use an SQL database which would have to be queried in order to relate the patient name to the file number. I think most of these files are the result of a cube scan so will have 128 separate images in them.
Regards

Mark

**Comment by marksgraham** [comment]
Hi Mark,

So there is no file saved for 'fda_testing_fundus.jpg' in the directory that you run the code from?

Can you try to use the FDS reader instead? So just modify the the FDS example so the filepath points to ` filepath = 'Z:\Public\OCT data\3DOCT_DATABASE\DATA\4867.fda`, and see if there is any luck extracting either an OCT or a fundus?

**Comment by Llew21** [comment]
Hi Mark
I tried the sample image and it converts that OK. It would seem that there is an incompatibility between the various sources of Topcon files. My machine is quite old and I believe that , in-spite of the extensions being the same, the file structure is different. Topcon say they have to be converted for their newer software to read them. They upgraded the firmware at one point and that may make a difference. Also you are expecting 5Mb files and mine are 11mb
If it's of interest I can send you one of my scans?
Regards

Mark

**Comment by Llew21** [comment]
I have experimented further:
here is the errors from both fds and fda scripts

C:\Users\Mark>C:\Users\Mark\OCT-Converter\examples\fda_extraction.py
Traceback (most recent call last):
  File "C:\Users\Mark\OCT-Converter\examples\fda_extraction.py", line 7, in <module>
    fda = FDA(filepath)
  File "c:\users\mark\oct-converter\oct_converter\readers\fda.py", line 38, in __init__
    self.chunk_dict = self.get_list_of_file_chunks()
  File "c:\users\mark\oct-converter\oct_converter\readers\fda.py", line 48, in get_list_of_file_chunks
    with open(self.filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\Public\\OCT data\\later samples2833.fda'

C:\Users\Mark>C:\Users\Mark\OCT-Converter\examples\fds_extraction.py
Traceback (most recent call last):
  File "C:\Users\Mark\OCT-Converter\examples\fds_extraction.py", line 6, in <module>
    fda = FDA(filepath)
NameError: name 'FDA' is not defined

C:\Users\Mark>

from oct_converter.readers import FDS

# An example .fds file can be downloaded from the Biobank website:
# https://biobank.ndph.ox.ac.uk/showcase/refer.cgi?id=30
filepath = 'Z:\Public\OCT data\later samples\62833.fda'
fda = FDA(filepath)
oct_volume = fds.read_oct_volume()  # returns an OCT volume with additional metadata if available
oct_volume.peek() # plots a montage of the volume
oct_volume.save('fds_testing.avi')  # save volume as a movie
oct_volume.save('fds_testing.png')  # save volume as a set of sequential images, fds_testing_[1...N].png

fundus_image = fds.read_fundus_image()  # returns a  Fundus image with additional metadata if available
fundus_image.save('62833.jpg')

and fda

from oct_converter.readers import FDA

# a sample .fda file can be downloaded from the Biobank resource here:
# https://biobank.ndph.ox.ac.uk/showcase/refer.cgi?id=31

filepath = 'Z:\Public\OCT data\later samples\62833.fda'
fda = FDA(filepath)
fundus_image = fda.read_fundus_image()  # returns a  Fundus image with additional metadata if available
fundus_image.save('62833.jpg')

I used one of the OCT's latest files to do this. Still no image to look at
regards
Mark

**Comment by marksgraham** [comment]
Hi Mark,

I would be keen to take a look if you were happy to share. Perhaps you could email me on mark [dot] graham [at] kcl.ac.uk?

Thanks!

**Comment by Llew21** [comment]
Hi Mark,

 

The file size of 11mb is ok?

 

Mark
